import React from 'react';

const DiscussionSection: React.FC = () => (
<section id="discussion">
  <h2>Discussion</h2>
  <p>When examining cultural norms of greetings, there are unspoken expectations that shape social interactions. While deviating from these norms can sometimes have a positive impact, not everyone is receptive to change, and such deviations can lead to undesired outcomes.  </p>
  <p>Additionally, when analyzing greeting preferences between men and women, a clear gender difference emerges. Research in cross-cultural psychology shows that nonverbal communication in Scandinavian countries tends to be less differentiated by gender, in line with their overall societal commitment to equality (Matsumoto & Juang, 2016). Showing how cultural effects have a greater influence on greeting preferences over innate desires. </p>
  <p>Although the survey indicated that sentiment toward handshakes is changing, it did not reveal a clear trend, and the sample size was insufficient for statistical analysis. However, COVID-19 had a significant impact, with 50% of respondents reporting that their perceptions of handshakes were influenced by the pandemic. The negative impact of COVID-19 on handshake norms is further supported by other polls (Gurchiek, 2023; Perret, 2020; Bruce, 2020). Additionally, Ballard’s (2020) poll found that 31% of Americans stated they would never shake hands again, reinforcing the broader societal shift away from this traditional greeting. One particular response illustrates how the norm is evolving, the respondent reported liking handshakes but almost never using them and not preferring them yet still expressed a desire for handshakes to be brought back. This highlights a key paradox: no matter how much someone wants a norm to persist, if people are not actively adhering to it, the norm will inevitably change. And this can be seen as 83% of respondents almost never use handshakes or use them less then 5 times per week. </p>
  <p>Additionally, with the exception of men in formal settings, other greeting preferences outweighed handshakes by a significant margin. While physical and non-physical greetings are starkly different, hugs and verbal greetings emerged as the top two choices, with only a 1.3% difference between them. However, when analyzing the data by gender, a notable difference appeared. Women preferred hugs by 2.3% more, whereas men showed the inverse trend, favoring verbal greetings by 8%. This close balance may be influenced by the effects of physical touch, which research suggests can lead to decreased blood pressure, increased oxytocin levels, improved attentiveness, and reduced depression. Conversely, a lack of touch may have the opposite effects (Field, 2010; Romney, 2023), leading to an innate need physical touch, handshake or otherwise. </p>
</section>
);

export default DiscussionSection;
