import React from 'react';

const ExperimentSection: React.FC = () => (
<section id="experiment">
  <h1>Disrupting Social Norms: Handshakes</h1>
  <p>While the pain of the COVID-19 pandemic was felt worldwide, there was one unexpected relief, the handshake was no longer an obligation. In the United States, the handshake is not only a common greeting but also a symbol of business, making it an expectation in professional settings. The handshake has even inspired books (Al-Shamahi, 2021) with many people believing they can determine a person’s personality through it. However, studies show mixed results, suggesting that other social factors are far more influential, making the handshake as a personality indicator largely insignificant (Ships & Freeman, 2003; Chaplin et al., 2000). Armed with this knowledge, my personal dislike for handshakes, and the lingering impact of COVID-19, I set out to challenge this cultural norm.  </p>
  <p>In February 2025, I attended a networking luncheon Northampton Community College. During the event, a panel of speakers provided students with advice on networking and building connections, emphasizing the importance of a firm handshake. After their presentation, we were divided into groups to practice networking with the presenters. When I approached my assigned presenter and they extended their hand for a handshake, I defied expectations and broke the norm. With enthusiasm, I raised my hand, palm forward, and offered a high-five, cheerfully saying, “Yay, team four!” Their expression shifted from awkwardness to a smile, instantly building rapport as we began to chat. Additionally, this unexpected gesture helped me stand out from the crowd an essential aspect of networking. However, the impact was short-lived. The presenters were there to practice networking, not to form genuine connections. While the high-five and enthusiasm initially created a positive and engaging atmosphere, it also disrupted the structured flow of the exercise, throwing the presenter off their script. Their attempts to steer the conversation back to traditional networking practices created tension, making the interaction feel forced and inauthentic. </p>
  <p>Despite my initial success with the high-five, it was clear that breaking a norm, can have unintended consequences. My experiment highlighted the deeply ingrained nature of handshakes in professional settings and how deviations from the norm can disrupt social interactions. This experience led me to wonder: How do others feel about handshakes? Do people value them, or do they simply comply out of habit or expectation? To answer these questions, I decided to do a survey and interviews to gain insight into public perceptions of handshakes. </p>
</section>
);

export default ExperimentSection;
